### ISSUE TITLE
gulp下面使用好像有问题

### ISSUE THREAD

**Issue by vibin-lin** [blackmiaool/decent-messup#2]
![image](https://user-images.githubusercontent.com/20037879/28633919-fa8f0dbe-7267-11e7-8e7e-d431733d2a03.png)

**Comment by blackmiaool** [comment]
windows下使用的话请检查路径的斜线方向

**Comment by blackmiaool** [comment]
请检查gulp.src里的文件是否存在

**Comment by blackmiaool** [comment]
没问题就关了哈

**Comment by vibin-lin** [comment]
您好, 文件是存在的, 我做了个最简单的demo也是不可以哦




![free-converter com-pasted_graphic_4-49321912](https://user-images.githubusercontent.com/20037879/28869411-33a41c56-77af-11e7-8785-1892fe17cbdf.jpg)
![free-converter com-pasted_graphic_3-15741919](https://user-images.githubusercontent.com/20037879/28869413-33b0af02-77af-11e7-93de-4d1787733068.jpg)
![free-converter com-pasted_graphic_2-99561918](https://user-images.githubusercontent.com/20037879/28869412-33afa224-77af-11e7-8354-0e67197ef03c.jpg)
![free-converter com-pasted_graphic_5-44442134](https://user-images.githubusercontent.com/20037879/28869491-71f1096a-77af-11e7-9f86-75625d3c1543.jpg)

**Comment by blackmiaool** [comment]
@vibin-lin 我更新了readme里面的demo, 照着改改就修复了  原因是gulp-transform那个插件更新了api....  
`.pipe(transform('utf8', code => messup(code,{headCnt:5,es6:true})))`

**Comment by vibin-lin** [comment]
多谢! 亲测能用了
