### ISSUE TITLE
There is a problem in  README

### ISSUE THREAD

**Issue by Tobepeter** [blackmiaool/decent-messup#3]
First I am very impressed that the idea the to mess up the code.
but when i try
The content in the usage of gulp may need to add

const gulp = require("gulp")

**Comment by blackmiaool** [comment]
It's not necessary to require gulp in a gulp plugin's readme.
Check https://github.com/futurechan/gulp-asset-transform and https://github.com/hemanth/gulp-jstransform

The snippet is supposed to be inserted in to a working gulpfile which is already containing a gulp require.
